from .models import ControlType

TAILORED_PROCEDURES: dict[ControlType, list[str]] = {
    ControlType.ACCESS_PROVISIONING: [
        "Obtain and inspect the access provisioning policy/procedure. Confirm the policy is formally approved, current, and covers the application in scope.",
        "Obtain the complete population of new user access requests provisioned during the audit period. Confirm completeness of the population with management.",
        "For a sample of new user access requests, confirm that a formal access request was submitted and documented prior to access being granted to the application.",
        "For the sample, confirm that documented approval from the user's line manager or an authorised approver was obtained before access was provisioned.",
        "For the sample, confirm that the access granted is commensurate with the user's job role and business need (principle of least privilege / role-based access).",
        "For the sample, confirm that access was provisioned within the timeframe specified in the policy/SLA.",
        "Confirm that segregation of duties (SoD) conflicts were considered and addressed during the provisioning process (where applicable).",
    ],
    ControlType.ACCESS_DEPROVISIONING: [
        "Obtain and inspect the access deprovisioning policy/procedure. Confirm the policy is formally approved and covers timely revocation upon termination or transfer.",
        "Obtain the population of user terminations and transfers during the audit period from HR. Confirm completeness of the population.",
        "For a sample of leavers, confirm that access to the application was fully revoked on or within the number of business days specified in the policy following the termination date.",
        "For the sample, confirm that the notification from HR (or the relevant department) to IT was performed in accordance with the defined process.",
        "For the sample, confirm that all forms of access were revoked, including standard user, privileged, shared, and any remote access accounts.",
        "For a sample of transfers, confirm that access was appropriately modified or removed based on the user's new role, and that prior role access was revoked.",
        "Confirm that terminated/transferred accounts are disabled or deleted in the system in line with the policy.",
    ],
    ControlType.PRIVILEGED_ACCESS: [
        "Obtain the complete and current list of users with privileged or administrator-level access to the application. Confirm completeness with management.",
        "For a sample of privileged users, confirm that there is documented business justification and formal management approval on file for the elevated access.",
        "Confirm that privileged access is restricted to the minimum level necessary for each user to perform their administrative responsibilities.",
        "Confirm that privileged accounts are not used for routine day-to-day non-administrative activities (i.e., separate accounts for administrative vs. standard tasks) where applicable.",
        "Confirm that activities performed using privileged accounts are subject to logging and that logs are reviewed on a periodic basis.",
        "Confirm that shared or generic privileged accounts (e.g., default admin accounts) are either prohibited or have documented compensating controls in place (e.g., password check-out, session recording).",
        "Confirm that privileged access is included in the periodic access recertification process.",
    ],
    ControlType.AUTHENTICATION: [
        "Obtain and inspect the authentication/password policy for the application. Confirm the policy aligns with industry standards (e.g., NIST SP 800-63, CIS Benchmarks).",
        "Confirm that minimum password length and complexity requirements (e.g., uppercase, lowercase, numbers, special characters) are configured and enforced at the system level.",
        "Confirm that password history and expiry/rotation requirements are enforced as per policy (or confirm a password-less/MFA approach is documented as an approved replacement).",
        "Confirm that account lockout is configured to trigger after the defined number of consecutive failed login attempts.",
        "Confirm that multi-factor authentication (MFA) is enforced for all users, or at minimum for privileged and remote access users.",
        "Confirm that session timeout is configured to automatically log out or lock inactive sessions after the defined period of inactivity.",
        "Confirm that default or shared credentials are not in use, or that compensating controls are documented and approved.",
    ],
    ControlType.DATABASE: [
        "Obtain the complete and current list of users with direct database access (e.g., DBA, read-only, reporting). Confirm completeness with management.",
        "Confirm that direct database access is restricted to authorised database administrators and that business users do not have direct access to the production database.",
        "Confirm that developers and other non-production support staff do not have direct production database access, supporting segregation of duties.",
        "Confirm that database activity logging and auditing is enabled, and that logs capture sufficient detail (e.g., user, timestamp, query type) for monitoring purposes.",
        "For a sample of direct data changes made outside the application, confirm that formal approval was obtained prior to the change being executed.",
        "Confirm that database administrator accounts are subject to periodic recertification and that the access list is reviewed for appropriateness.",
        "Confirm that database connection credentials used by application service accounts are appropriately secured (e.g., not stored in plain text, subject to rotation).",
    ],
    ControlType.RECERTIFICATION: [
        "Obtain and inspect the user access recertification (UAR) policy/procedure. Confirm the policy specifies the review frequency, scope, and responsible reviewers.",
        "Obtain evidence of all recertification exercises completed during the audit period. Confirm recertifications were performed at the frequency specified in the policy.",
        "Confirm that the recertification was performed by appropriate reviewers (e.g., line managers, system owners, data owners) with sufficient knowledge of users' access requirements.",
        "For a sample of user certifications, confirm that reviewers certified or rejected access in a documented and evidenced manner (i.e., not a blanket approval without review).",
        "Confirm that access identified as no longer required or inappropriate during the review was revoked within the timeframe specified in the policy.",
        "Confirm that the results of the recertification exercise, including actions taken for revoked access, were documented and communicated to management.",
        "Confirm that privileged access accounts were included in the scope of the recertification exercise.",
    ],
    ControlType.CHANGE_MANAGEMENT_CODE: [
        "Obtain and inspect the change management policy/procedure. Confirm the policy covers the full lifecycle of code changes including request, testing, approval, and deployment.",
        "Obtain the population of code changes (including patches and releases) deployed to the production environment during the audit period. Confirm completeness.",
        "For a sample of code changes, confirm that a formal change request (ticket/RFC) was raised and documented prior to deployment.",
        "For the sample, confirm that changes were tested in a non-production environment (e.g., development, UAT, staging) before promotion to production.",
        "For the sample, confirm that appropriate and documented approval was obtained from an authorised approver before the change was deployed to production.",
        "Confirm that segregation of duties exists between those who develop/write code and those who approve and promote code to production.",
        "For a sample of emergency/urgent changes, confirm that these were subject to retrospective approval and documented in accordance with the emergency change policy.",
    ],
    ControlType.CHANGE_MANAGEMENT_CONFIG: [
        "Obtain and inspect the change management policy/procedure. Confirm the policy covers configuration changes and specifies the required controls.",
        "Obtain the population of configuration changes made to the application/environment during the audit period. Confirm completeness.",
        "For a sample of configuration changes, confirm that a formal change request was raised and that the change was documented, including the reason for the change.",
        "For the sample, confirm that appropriate authorisation from management or an approved change authority was obtained before the configuration change was implemented.",
        "For the sample, confirm that configuration changes were tested in a non-production environment or that the impact was assessed and documented before implementation.",
        "Confirm that configuration change logs are maintained and subject to periodic management review to detect unauthorised changes.",
        "Confirm that rollback plans or the ability to revert configurations are documented and tested for significant configuration changes.",
    ],
}
